# Generated by Django 4.2.3 on 2024-12-05 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('bloco', models.IntegerField()),
                ('capacidade', models.IntegerField()),
                ('tipo', models.CharField(max_length=20)),
                ('disponivel', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
        ),
        migrations.CreateModel(
            name='CondominioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casa_numero', models.IntegerField()),
                ('hora_inicio', models.DateTimeField()),
                ('hora_fim', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.DeleteModel(
            name='Condominio',
        ),
    ]
