# Generated by Django 4.2.3 on 2024-12-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio', '0002_casamodel_condominiomodel_delete_condominio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='condominiomodel',
            options={'verbose_name': 'Condomínio', 'verbose_name_plural': 'Condomínios'},
        ),
        migrations.RemoveField(
            model_name='casamodel',
            name='capacidade',
        ),
        migrations.RemoveField(
            model_name='casamodel',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='condominiomodel',
            name='hora_fim',
        ),
        migrations.RemoveField(
            model_name='condominiomodel',
            name='hora_inicio',
        ),
        migrations.AddField(
            model_name='casamodel',
            name='area_lazer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casamodel',
            name='garagem',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casamodel',
            name='quantidade_banheiros',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='casamodel',
            name='quantidade_quartos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='condominiomodel',
            name='endereco',
            field=models.CharField(default='Endereço não especificado', max_length=250),
        ),
        migrations.AlterField(
            model_name='casamodel',
            name='disponivel',
            field=models.BooleanField(default=False),
        ),
    ]
