# Generated by Django 5.1.4 on 2024-12-06 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='cpf',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
